C**************************
        SUBROUTINE AMC(NCODP,QREF)
	use var
!WC	Esta sub-rotina foi alterada para ser usada no programa IPHS1
!WC	adaptado para os trabalhos do 
!WC	Plano de Drenagem Urbana da Regiao Metropolitana de Curitiba
!WC	
!WC			Walter Collischonn IPH-UFRGS  -  janeiro de 2000
!WC
!WC	A principal alteraçao foi a inclusao de uma rotina que estima o
!WC	numero de subtrechos adequado para a simulaçao.
	REAL,ALLOCATABLE:: QM(:),QC(:,:),QCOR(:),QL(:)
C	      DIMENSION QM(3000),QC(20,3000),QCOR(3000),QL(3000)
        COMMON /DATA/Q(300,200),IPL(200),QMAX,QMIN,IS,IE,IPP,NPL,NT,
     1PRE(300),AT,QO(300),IOBS,IPR,ILIST,PA(300),PEF(300),NTT,PER(300),
     2PMAX,VOP(300),P(300,10)
	REAL B,ALONG,SO,DTCAL,DX,RUG
	INTEGER NTRECH,ILAT
        READ(1,11)B,ALONG,SO,DTCAL,NTRECH,RUG,ILAT
!!WC WRITE(*,11)B,ALONG,SO,DTCAL,NTRECH,RUG,ILAT
!WC	QREF EH SUBSTITUÍDA POR 2/3 DA VAZAO MAXIMA DE MONTANTE SE QREF=0.
	if(Qref==0.)then
      QMMX=0.0
	DO IWC=1,NT
		IF(Q(IWC,IE).GT.QMMX)THEN
			QMMX=Q(IWC,IE)
		ENDIF
	ENDDO
	QREF=QMMX*2./3. !AQUI QREF É SUBSTITUÍDA
      endif
	IF(DTCAL==0.)DTCAL=AT  !SE DTCAL NAO E DEFINIDO ADOTA O DA SIMULAÇAO
!WC
	COEF=1.67*SO**0.3/RUG**0.6
 
	CEL=COEF*(QREF/B)**0.4
	QESP=QREF/B

	automatico: if (ntrech.eq.0)then
C	CEL=QESP/(((QESP*RUG)/SO**0.5)**0.6)
	H1=0.1*(((QESP*RUG)/SO**0.5)**0.6) !PROFUNDIDADE EM METROS (1 ESTIMATIVA)
	H2=10.*(((QESP*RUG)/SO**0.5)**0.6) !PROFUNDIDADE EM METROS (2 ESTIMATIVA)
	XACC=0.001*QREF
C	CALCULA PROFUNDIDADE E ESTIMA A CELERIDADE (dQ/dA = dQ/dH*(1/B) )
	CALL NEWT2(H,H1,H2,XACC,QREF,B,SO,RUG,CEL)
	VEL=((((B*H)/(B+2.*H))**0.667)*SO**0.5)/RUG
!WC	Aqui é calculado o melhor numero de trechos NTRECH 
!WC	esta mudança só vale para Muskingum Cunge linear
	DTCAL=AT !POR UMA QUESTAO DE SEGURANÇA
	IWCT=1
C	DX=(2.5*QREF)/(B*SO*CEL) !ESTIMATIVA INICIAL DE DX
	DX1=0.5 !VALOR ARBITRARIO BEM PEQUENO
	DX2=ALONG*100000.
	XACC=0.5 !ERRO ADMITIDO NA RAIZ
1919	CALL NEWTRAP(RTSAFE,DX1,DX2,xacc,QREF,B,SO,CEL,DTCAL)
	DX=RTSAFE
!WC	TESTA ESTE DX 
	IF((ABS(DX-ALONG))/ALONG.LT.0.1.OR.DX/ALONG.LT.0.6)THEN
		XTRECH=ALONG/DX
		NTRECH=NINT(XTRECH)
C		NTRECH=NINT(ALONG/DX)
	ELSE
		IWCT=IWCT+1
		IF(IWCT.GT.10)THEN 	!DESISTE DE DIMINUIR DTCAL E USA DX=ALONG
			WRITE(*,*) 'DX=ALONG,  DTCAL=',DTCAL
			write(9,*)'OPERAÇAO',ca
			WRITE(9,*)'VALOR DE CALCULO','DX=ALONG,  DTCAL=',DTCAL
              NTRECH=1
			GOTO 2019
		ENDIF
		DTCAL=AT/IWCT !VAI DIMINUINDO DTCAL,MAS MANTEM MULTIPLO DE AT
		GOTO 1919
	ENDIF

	NCALC=AT/DTCAL*(NT-1)+1  !trechos de calculo, usa o DT calculado

	endif automatico
      DX=ALONG/NTRECH

701   IF(NCODP.EQ.3)GO TO 501 !MUSKINGUM-CUNGE NAO LINEAR

!      parametros lineares
2019	AK=DX/CEL
	XXX=0.5 - (0.5*QESP/SO)/CEL/DX
	DEN=2*AK*(1- XXX)+DTCAL
	C1=(2*AK*XXX+DTCAL)/DEN
	C2=(DTCAL-2*AK*XXX)/DEN
	C3=(2*AK*(1-XXX)-DTCAL)/DEN


	NCALC=AT/DTCAL*(NT-1)+1
	ALLOCATE (QM(NCALC),QC(NTRECH+1,NCALC),QCOR(NCALC),QL(NCALC))



501     DO 202 K=1,NT
202     QM(K)=Q(K,IE)
CW        WRITE(*,1)NCODP
   1    FORMAT(I10) 


	DO 24 I=1,NTRECH+1
	DO 24 J=1,NCALC
24      QC(I,J)=0.
	DX=ALONG/NTRECH
	IF(DTCAL.EQ.AT)GO TO 80
	NCALC=AT/DTCAL*(NT-1)+1
	N=AT/DTCAL
	DO 90 I=1,NT-1
	DO 110 J=N*(I-1)+1,N*(I-1)+N
        QL(J)=0
        IF(ILAT.NE.0)QL(J)=(Q(I,ILAT)+(Q(I+1,ILAT)-Q(I,ILAT))
     1*(J-(N*(I-1)+1))/(1.*N))/ALONG
110	QCOR(J)=Q(I,IE)+(Q(I+1,IE)-Q(I,IE))*(J-(N*(I-1)+1))/(1.*N)
 90	CONTINUE
	QCOR(NCALC)=Q(NT,IE)
	GO TO 120
 80	NCALC=NT
	N=1
!!WCWRITE(*,11)ALONG
	DO 130 I=1,NT
        QL(I)=0
        IF(ILAT.NE.0)QL(I)=Q(I,ILAT)/ALONG
130	QCOR(I)=QM(I)
C	CONDICAO INICIAL
120	DO 20 J=1,NTRECH+1
20 	QC(J,1)=QCOR(1)
C
C	CONDICAO DE CONTORNO
C
	DO 30 N=2,NCALC
30	QC(1,N)=QCOR(N)
	DO 40 J=1,NTRECH
	DO 50 N=1,NCALC-1
        C4= 2*QL(N)*DTCAL*DX
107     IF(NCODP.EQ.2)GO TO 399  !SE E LINEAR PULA O CALCULO DE COEFICIENTES EM CADA INTERVALO DE TEMPO
	Q1=QC(J,N)/B
	Q2=QC(J+1,N)/B
	Q3=QC(J,N+1)/B
        IF((Q1.EQ.0.).AND.(Q2.EQ.0.).AND.(Q3.EQ.0))GO TO 55
	CEL=COEF*(Q1**0.4+Q2**0.4+Q3**0.4)/3.
	QESP=(Q1+Q2+Q3)/3.
	AK=DX/CEL
	XXX=0.5 - (0.5*QESP/SO)/CEL/DX
	D=(QESP/SO)/CEL/DX
	DEN=2*AK*(1- XXX)+DTCAL
	C1=(2*AK*XXX+DTCAL)/DEN
	C2=(DTCAL-2*AK*XXX)/DEN
	C3=(2*AK*(1-XXX)-DTCAL)/DEN
399     C4=C4/DEN
        QC(J+1,N+1)=C1*QC(J,N)+C2*QC(J,N+1)+C3*QC(J+1,N)+C4
        GO TO 50
55      QC(J+1,N+1)=0.
50	CONTINUE
40	CONTINUE
        N=AT/DTCAL
        DO 1040 I=1,NT
1040    Q(I,IS)=QC(NTRECH+1,1+(I-1)*N)
        WRITE(2,209)DX,RUG,B,SO,DTCAL,NTRECH
209     FORMAT(//10X,'PARAMETROS',
     1//10X,'AX',6X,'N',
     14X,'LARGURA',4X,'DECLIVIDADE',4X,'INT. TEMPO',4X,' NTRECH ',
     1/ 9X,' M ',13X,' M ',9X,' M/M ',9X,' SEG',/
     1(F12.1,F7.3,F11.1,F15.5,F14.0,I11))
11	FORMAT(4F10.0,I10,F10.0,I10)
      
      !--------------------------------
      write(8,778)is,1  !escreve as cotas
778	FORMAT('ophid',I5,f10.2)

      QMAX=MAXVAL(Q(:,is))

      	
      do I=1,nt
	cot=Q(I,is)/QMAX
 
      write(8,12)cot
      enddo !do impresao cota
      !-----------------------------------
12    format (f10.3)

	DEALLOCATE (QM,QC,QCOR,QL)

        RETURN
        END
C**************************
