      SUBROUTINE AMCP
	USE VAR

      DIMENSION H(15),QT(16),CEL(15),AK(15),XXX(15)
	REAL,ALLOCATABLE:: QM(:),QC(:,:),QCOR(:),QL(:)

	READ(1,'(3F10.0)')QREF !LE PARA MANTER O MESMO PADRAO DE ENTRADA
      READ(1,'(6F10.2,I10,F10.3,I10)')
	1B,Y0,ALONG,COTMON,COTJUS,DTCAL,NTRECH,RUG,ILAT
      READ(1,'(3F10.0)')B1,RUG1,Y1

	SO=(COTMON-COTJUS)/ALONG !calcula a declividade

!WC	QREF EH SUBSTITUÍDA POR 2/3 DA VAZAO MAXIMA DE MONTANTE se QREF=0
	vazao referencia: if (QREF==0.)then
		QMMX=0.0
			DO IWC=1,NT
				IF(Q(IWC,IE).GT.QMMX)THEN
				QMMX=Q(IWC,IE)
				ENDIF
			ENDDO
		QREF=QMMX*2./3. !AQUI QREF É SUBSTITUÍDA
      endif vazao referencia

      AUTOM: IF(nTRECH.LE.0)THEN
!		ESTIMATIVA DO NUMERO DE SUBTRECHOS E DO DTCAL, CONSIDERANDO ESCOAMENTO
!		APENAS NO CANAL PRINCIPAL
		QESP=QREF/B
		H1=0.1*(((QESP*RUG)/SO**0.5)**0.6) !PROFUNDIDADE EM METROS (1 ESTIMATIVA)
		H2=10.*(((QESP*RUG)/SO**0.5)**0.6) !PROFUNDIDADE EM METROS (2 ESTIMATIVA)
		XACC=0.001*QREF
!		CALCULA PROFUNDIDADE E ESTIMA A CELERIDADE (dQ/dA = dQ/dH*(1/B) )
		CALL NEWT2(HB,H1,H2,XACC,QREF,B,SO,RUG,CELB)
		VEL=((((B*HB)/(B+2.*HB))**0.667)*SO**0.5)/RUG
!		Aqui é calculado o melhor numero de trechos NTRECH 
!		esta mudança só vale para Muskingum Cunge linear
		DTCAL=AT/10. !POR UMA QUESTAO DE SEGURANÇA
		IWCT=1
!		DX=(2.5*QREF)/(B*SO*CEL) !ESTIMATIVA INICIAL DE DX
		DX1=0.5 !VALOR ARBITRARIO BEM PEQUENO
		DX2=ALONG*100000.
		XACC=0.5 !ERRO ADMITIDO NA RAIZ
1919		CALL NEWTRAP(RTSAFE,DX1,DX2,xacc,QREF,B,SO,CELB,DTCAL)
		DX=RTSAFE
!		TESTA ESTE DX 
			IF((ABS(DX-ALONG))/ALONG.LT.0.1.OR.DX/ALONG.LT.0.6)THEN
				NTRECH=NINT(ALONG/DX)
!					IF(NTRECH.GT.20)THEN 
!						WRITE(*,*)'NUMERO DE SUB-TRECHOS MAIOR QUE 20!!!'
!					ENDIF
			ELSE
				IWCT=IWCT+1
				IF(IWCT.GT.10)THEN 	!DESISTE DE DIMINUIR DTCAL E USA DX=ALONG
					WRITE(*,*) 'DX=ALONG,  DTCAL=',DTCAL
					write(9,*)'OPERAÇAO ',ca
					WRITE(9,*)'VALOR DE CALCULO','DX=ALONG,  DTCAL=',DTCAL
					NTRECH=1
					GOTO 2019
				ENDIF
			DTCAL=(AT/2.)/IWCT !VAI DIMINUINDO DTCAL,MAS MANTEM MULTIPLO DE AT
			GOTO 1919
			ENDIF
	ENDIF AUTOM

2019  DH=Y0/10.
      DX=ALONG/NTRECH
	COEF=1.67*SO**0.3/RUG**0.6


!WC	DEFINE QUANTOS INTERVALOS DE TEMPO DE CALCULO VAI existir E DIMENSIONA MATRIZES
	IF(DTCAL.EQ.AT)THEN
		NCALC=NT
	ELSE
		NCALC=AT/DTCAL*(NT-1)+1
	ENDIF

	ALLOCATE (QM(NCALC),QC(NTRECH+1,NCALC),QCOR(NCALC),QL(NCALC)) !!WC
!WC	FIM DA DEFINIÇÃO DE QUANTOS INTERVALOS DE TEMPO DE CALCULO VAI HAVER
!WC	F=(B*H*(((B*H)/(B+2.*H))**0.667)*SO**0.5)/RUG-Q

     
	DO 55 I=1,15
		H(I)=I*DH
		HB=H(I)	 !!WC
		!CONSIDERANDO O ATRITO COM AS PAREDES
		QT(I)=(B*HB*(((B*HB)/(B+2.*HB))**0.667)*SO**0.5)/RUG !!WC
C		QT(I)=SO**0.5*B*H(I)**1.67/RUG
		HB=HB+DH !AUMENTA UM POUCO PROFUNDIDADE !!WC
		QT(I+1)=(B*HB*(((B*HB)/(B+2.*HB))**0.667)*SO**0.5)/RUG !!WC
		DQDH=(QT(I+1)-QT(I))/DH !!WC
		CEL(I)=DQDH/B	!!WC
C		CEL(I)=COEF*(QT(I)/B)**0.4
		AK(I)=DX/CEL(I)
		XXX(I)=0.5 - (0.5*QT(I)/B/SO)/CEL(I)/DX
55	CONTINUE

      DO 70 I=11,15
		DH1=I*DH-Y0
		QT(I)=QT(I)+SO**0.5*B1*DH1**1.67/RUG1
		CEL(I)=1.67*SO**0.5*(B/RUG*(Y0+DH1)**0.67
     1	+B1/RUG1*DH1**0.67)
		CEL(I)=CEL(I)/(B+B1)
		AK(I)=DX/CEL(I)
		XXX(I)=0.5-(0.5*QT(I)/(B+B1)/SO)/CEL(I)/DX
70    CONTINUE

!WC	MUDA OS PARAMETROS PARA A VAZAO MAIS BAIXA
!WC	PARA EVITAR VALORES NEGATIVOS NA SUBIDA BRUSCA DO HIDROGRAMA
	IREF=2
	DO KW=1,IREF-1
		AK(KW)=AK(IREF)
		XXX(KW)=XXX(IREF)
	ENDDO
!WC	FIM DA MUDANCA

      WRITE(2,209)DX,RUG,B,SO,DTCAL,NTRECH,B1,RUG1,Y0
      WRITE(2,7)(K,H(K),CEL(K),XXX(K),AK(K),QT(K),K=1,15)
      
	DO 202 K=1,NT
202   QM(K)=Q(K,IE)

	DO 24 I=1,NTRECH+1
24    QC(I,:)=0.

	DX=ALONG/NTRECH

	IF(DTCAL.EQ.AT)THEN
		NCALC=NT
		GO TO 80
	ENDIF
	NCALC=AT/DTCAL*(NT-1)+1

	N=AT/DTCAL

	DO 90 I=1,NT-1
		DO 110 J=N*(I-1)+1,N*(I-1)+N
			QL(J)=0
			IF(ILAT.NE.0)THEN
				QL(J)=(Q(I,ILAT)+(Q(I+1,ILAT)-Q(I,ILAT))
     1			*(J-(N*(I-1)+1))/(1.*N))/ALONG
			ENDIF
			QCOR(J)=Q(I,IE)+(Q(I+1,IE)-Q(I,IE))*(J-(N*(I-1)+1))/(1.*N)
110		CONTINUE
 90	CONTINUE

	QCOR(NCALC)=Q(NT,IE)
	GO TO 120
 80	NCALC=NT
	N=1

	DO 130 I=1,NT
		QL(I)=0
		IF(ILAT.NE.0)THEN
			QL(I)=Q(I,ILAT)/ALONG
		ENDIF
		QCOR(I)=QM(I)
130	CONTINUE

120	DO 20 J=1,NTRECH+1
20 	QC(J,1)=QCOR(1)

	DO 30 N=2,NCALC
30	QC(1,N)=QCOR(N)

	DO 40 J=1,NTRECH
		DO 50 N=1,NCALC-1

			W1=0.33
			W2=0.33
			W3=0.34

			W1=3.0*W1
			W2=3.0*W2
			W3=3.0*W3

		
			QQ=(W1*QC(J,N)+W2*QC(J+1,N)+W3*QC(J,N+1))/3.
				

			IF(QQ.LT.QT(1))THEN
				QQ=QT(1)
			ENDIF
			XX=FINT(QT,XXX,15,QQ)
			XKK=FINT(QT,AK,15,QQ)
			DEN=2*XKK*(1- XX)+DTCAL
			C1=(2*XKK*XX+DTCAL)/DEN
			C2=(DTCAL-2*XKK*XX)/DEN
			C3=(2*XKK*(1-XX)-DTCAL)/DEN
			C4=2*QL(N)*DX*DTCAL/DEN
			QC(J+1,N+1)=C1*QC(J,N)+C2*QC(J,N+1)+C3*QC(J+1,N)+C4
			QC(J+1,N+1)=MAX(0.0,QC(J+1,N+1)) !!WC
50		CONTINUE
40	CONTINUE

      N=AT/DTCAL
      DO 1040 I=1,NT
1040  Q(I,IS)=QC(NTRECH+1,1+(I-1)*N)
209     FORMAT(//10X,'PARAMETROS',
     1//10X,'AX',6X,'N',
     14X,'B ',4X,'SO',4X,'DTCAL',4X,'NTRECH',4X,'BPLAN',4X,'NPLAN',4X,
     1'Y0'
     1/ 9X,'(M)',10X,'(M)',2X,'(M/M)',3X,'(SEG)',15X,'(M)',13X,'(M)',/,/
     1(F12.1,F7.3,F5.1,F7.4,F9.0,I10,F9.1,F9.3,F6.2))
7	FORMAT(//10X,'TRECHO EN CANAL COM PLANICIE DE INUNDACAO',
     1///,9X,'I',9X,'H',7X,'CEL', 9X,'X',9X,
     1'K',5X,'VAZAO',/,
     119X,'M',7X,'M/S',18X,'HS',6X,'M3/S',/,
     1100(I10,F10.2,4F10.2/)//)


	DEALLOCATE (QM,QC,QCOR,QL) !!WC

      !--------------------------------
      write(8,778)is,H(15),1  !escreve as cotas
778	FORMAT('ophid',I5,f10.2,I10)
      cot=0.
      do i=1,nt
      cot=Fint(QT,h,15,Q(i,is))
	write(8,'(f10.3)')cot
      enddo
      !-----------------------------------


        RETURN
        END
C**************************
